<?php $order = $this->getOrder() ?>
<div class="entry-edit box-left">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo $this->__('Radial Tax, Duties, Fees Service') ?></h4>
    </div>
    <fieldset>
        <div id="radial_tax_displayerror">
            <span><?php echo Mage::helper('core')->__($this->getNoTaxErrorMessage()); ?></span>
        </div>
    </fieldset>
</div>
<div class="clear"></div>
